name: Discord Webhook
on:
    push:
        branches:
            - main
jobs:
    discord_push_webhook:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run Discord Webhook
              uses: kokiriglade/classic-discord-webhook@1.1.1
              with:
                  id: ${{ secrets.DISCORD_WEBHOOK_ID }}
                  token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
