name: Deploy Javadoc

on:
  release:
    branches:
      - main
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          target-folder: javadoc
          project: gradle
          javadoc-source-folder: popcorn/build/docs/javadoc